### ISSUE TITLE
CONFIG_PWM_GPIO

### ISSUE THREAD

**Issue by pyavitz** [tobetter/linux#32]
The following [commit](https://github.com/tobetter/linux/commit/561b3debb2fc9c098f2e7a1ce47c87176a92b2b1#diff-cf1b8827bdb99925291507eaecb76f3da89aa7b0082abb03a5018dfa38c97143R232) seems to be broken on 5.15.y.

```sh
drivers/pwm/pwm-gpio.c: In function ‘gpio_pwm_remove’:
drivers/pwm/pwm-gpio.c:232:9: error: void value not ignored as it ought to be
  232 |  return pwmchip_remove(&gpio_chip->chip);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/pwm/pwm-gpio.c:233:1: error: control reaches end of non-void function [-Werror=return-type]
```
Unless its me? But it compiles fine on 5.14.15

**Comment by pyavitz** [comment]
In my testing the following seems to correct the problem and bring the fan back to life.

```sh
--- a/drivers/pwm/pwm-gpio.c	2021-10-30 06:18:02.000000000 -0400
+++ b/drivers/pwm/pwm-gpio.c	2021-11-01 13:09:47.822237106 -0400
@@ -229,7 +229,9 @@
 		hrtimer_cancel(&gpio_data->timer);
 	}
 
-	return pwmchip_remove(&gpio_chip->chip);
+	pwmchip_remove(&gpio_chip->chip);
+	
+	return 0;
 }
 
 static const struct of_device_id gpio_pwm_of_match[] = {

```

**Comment by tobetter** [comment]
Thanks, I didn't aware of this yet. The fix has been uploaded. :)
https://github.com/tobetter/linux/commit/817779d3e11400515fdb46ec2bade03b6bd5139a

**Comment by pyavitz** [comment]
Thanks
